// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jul  3 2024 15:06:42 IST (Jul  3 2024 09:36:42 UTC)

// Verification Directory fv/CAN_Controller 

module CAN_Controller(clk, rst, id, data, send, tx, busy);
  input clk, rst, send;
  input [10:0] id;
  input [7:0] data;
  output tx, busy;
  wire clk, rst, send;
  wire [10:0] id;
  wire [7:0] data;
  wire tx, busy;
  wire [3:0] bit_cnt;
  wire [7:0] data_reg;
  wire [10:0] id_reg;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51;
  DFFSHQX1 tx_reg(.SN (n_48), .CK (clk), .D (n_51), .Q (tx));
  OR4XL g1947__8780(.A (n_39), .B (n_38), .C (n_50), .D (n_49), .Y
       (n_51));
  OAI211XL g1967__4296(.A0 (n_8), .A1 (n_10), .B0 (n_34), .C0 (n_47),
       .Y (n_50));
  OAI21X1 g1949__3772(.A0 (n_46), .A1 (n_43), .B0 (n_31), .Y (n_49));
  DFFRHQX1 \bit_cnt_reg[1] (.RN (n_48), .CK (clk), .D (n_45), .Q
       (bit_cnt[1]));
  NAND4XL g1978__1474(.A (bit_cnt[2]), .B (n_46), .C (n_42), .D (n_28),
       .Y (n_47));
  INVXL g1980(.A (n_40), .Y (n_45));
  OAI2BB1XL g1966__4547(.A0N (n_11), .A1N (n_32), .B0 (n_27), .Y
       (n_44));
  AOI32X1 g1968__9682(.A0 (tx), .A1 (n_42), .A2 (n_2), .B0 (n_4), .B1
       (n_24), .Y (n_43));
  SDFFQXL \data_reg_reg[3] (.CK (clk), .D (data_reg[3]), .SI (data[3]),
       .SE (n_41), .Q (data_reg[3]));
  SDFFQXL \id_reg_reg[6] (.CK (clk), .D (id_reg[6]), .SI (id[6]), .SE
       (n_41), .Q (id_reg[6]));
  SDFFQXL \id_reg_reg[9] (.CK (clk), .D (id_reg[9]), .SI (id[9]), .SE
       (n_41), .Q (id_reg[9]));
  SDFFQXL \data_reg_reg[0] (.CK (clk), .D (data_reg[0]), .SI (data[0]),
       .SE (n_41), .Q (data_reg[0]));
  SDFFQXL \data_reg_reg[1] (.CK (clk), .D (data_reg[1]), .SI (data[1]),
       .SE (n_41), .Q (data_reg[1]));
  SDFFQXL \id_reg_reg[4] (.CK (clk), .D (id_reg[4]), .SI (id[4]), .SE
       (n_41), .Q (id_reg[4]));
  SDFFQXL \id_reg_reg[5] (.CK (clk), .D (id_reg[5]), .SI (id[5]), .SE
       (n_41), .Q (id_reg[5]));
  SDFFQXL \id_reg_reg[10] (.CK (clk), .D (id_reg[10]), .SI (id[10]),
       .SE (n_41), .Q (id_reg[10]));
  SDFFQXL \id_reg_reg[0] (.CK (clk), .D (id_reg[0]), .SI (id[0]), .SE
       (n_41), .Q (id_reg[0]));
  SDFFQXL \id_reg_reg[8] (.CK (clk), .D (id_reg[8]), .SI (id[8]), .SE
       (n_41), .Q (id_reg[8]));
  SDFFQXL \id_reg_reg[7] (.CK (clk), .D (id_reg[7]), .SI (id[7]), .SE
       (n_41), .Q (id_reg[7]));
  SDFFQXL \data_reg_reg[6] (.CK (clk), .D (data_reg[6]), .SI (data[6]),
       .SE (n_41), .Q (data_reg[6]));
  SDFFQXL \data_reg_reg[7] (.CK (clk), .D (data_reg[7]), .SI (data[7]),
       .SE (n_41), .Q (data_reg[7]));
  SDFFQXL \id_reg_reg[3] (.CK (clk), .D (id_reg[3]), .SI (id[3]), .SE
       (n_41), .Q (id_reg[3]));
  SDFFQXL \id_reg_reg[1] (.CK (clk), .D (id_reg[1]), .SI (id[1]), .SE
       (n_41), .Q (id_reg[1]));
  SDFFQXL \id_reg_reg[2] (.CK (clk), .D (id_reg[2]), .SI (id[2]), .SE
       (n_41), .Q (id_reg[2]));
  SDFFQXL \data_reg_reg[2] (.CK (clk), .D (data_reg[2]), .SI (data[2]),
       .SE (n_41), .Q (data_reg[2]));
  SDFFQXL \data_reg_reg[5] (.CK (clk), .D (data_reg[5]), .SI (data[5]),
       .SE (n_41), .Q (data_reg[5]));
  SDFFQXL \data_reg_reg[4] (.CK (clk), .D (data_reg[4]), .SI (data[4]),
       .SE (n_41), .Q (data_reg[4]));
  AOI222XL g1982__2683(.A0 (n_20), .A1 (n_5), .B0 (bit_cnt[1]), .B1
       (n_35), .C0 (n_29), .C1 (n_15), .Y (n_40));
  AOI211X1 g1981__1309(.A0 (n_9), .A1 (n_18), .B0 (bit_cnt[2]), .C0
       (n_37), .Y (n_39));
  AOI211X1 g1979__6877(.A0 (n_7), .A1 (n_19), .B0 (n_22), .C0 (n_37),
       .Y (n_38));
  AO22XL g1965__2900(.A0 (n_26), .A1 (n_23), .B0 (bit_cnt[2]), .B1
       (n_35), .Y (n_36));
  AOI32X1 g1991__2391(.A0 (id_reg[3]), .A1 (n_25), .A2 (n_30), .B0
       (tx), .B1 (n_35), .Y (n_34));
  OAI211X1 g1951__7675(.A0 (n_12), .A1 (n_32), .B0 (n_37), .C0 (n_13),
       .Y (n_33));
  AOI31X1 g1984__7118(.A0 (id_reg[0]), .A1 (n_16), .A2 (n_30), .B0
       (n_14), .Y (n_31));
  SDFFRHQX1 \bit_cnt_reg[0] (.RN (n_48), .CK (clk), .D (n_29), .SI
       (n_35), .SE (bit_cnt[0]), .Q (bit_cnt[0]));
  NAND2XL g1990__8757(.A (n_6), .B (n_21), .Y (n_28));
  AOI31XL g1989__1786(.A0 (bit_cnt[2]), .A1 (n_26), .A2 (n_25), .B0
       (n_35), .Y (n_27));
  INVXL g1987(.A (n_17), .Y (n_24));
  MXI2XL g2001__5953(.A (n_22), .B (bit_cnt[2]), .S0 (n_25), .Y (n_23));
  AOI22XL g1998__5703(.A0 (n_20), .A1 (id_reg[6]), .B0 (n_25), .B1
       (id_reg[7]), .Y (n_21));
  NAND2XL g2007__7114(.A (state[0]), .B (n_26), .Y (n_37));
  SDFFRHQX1 \state_reg[1] (.RN (n_48), .CK (clk), .D (n_1), .SI
       (state[1]), .SE (n_42), .Q (state[1]));
  AOI22X1 g1992__5266(.A0 (data_reg[6]), .A1 (n_20), .B0 (data_reg[7]),
       .B1 (n_25), .Y (n_19));
  AOI22X1 g1993__2250(.A0 (data_reg[2]), .A1 (n_20), .B0 (data_reg[3]),
       .B1 (n_25), .Y (n_18));
  AOI222XL g1988__6083(.A0 (id_reg[8]), .A1 (n_16), .B0 (id_reg[10]),
       .B1 (n_20), .C0 (n_15), .C1 (id_reg[9]), .Y (n_17));
  SDFFRHQX1 busy_reg(.RN (n_48), .CK (clk), .D (busy), .SI (send), .SE
       (n_14), .Q (busy));
  NOR2X2 g1996__2703(.A (rst), .B (n_13), .Y (n_41));
  NAND2XL g2002__5795(.A (n_42), .B (n_11), .Y (n_12));
  AOI22X1 g2000__7344(.A0 (id_reg[1]), .A1 (n_15), .B0 (id_reg[2]), .B1
       (n_20), .Y (n_10));
  AOI22X1 g1999__1840(.A0 (data_reg[0]), .A1 (n_16), .B0 (data_reg[1]),
       .B1 (n_15), .Y (n_9));
  CLKINVX1 g2005(.A (n_8), .Y (n_30));
  AOI22X1 g1994__5019(.A0 (data_reg[4]), .A1 (n_16), .B0 (data_reg[5]),
       .B1 (n_15), .Y (n_7));
  AOI22X1 g1997__1857(.A0 (id_reg[4]), .A1 (n_16), .B0 (id_reg[5]), .B1
       (n_15), .Y (n_6));
  OAI2BB1XL g2006__9906(.A0N (state[1]), .A1N (n_22), .B0 (n_3), .Y
       (n_5));
  OAI2BB1X1 g1995__8780(.A0N (state[1]), .A1N (n_4), .B0 (n_3), .Y
       (n_29));
  CLKINVX1 g1983(.A (n_2), .Y (n_32));
  NAND2XL g2003__4296(.A (n_14), .B (send), .Y (n_13));
  NOR2XL g2004__3772(.A (n_42), .B (n_1), .Y (n_35));
  NAND2XL g2008__1474(.A (n_46), .B (n_4), .Y (n_8));
  NAND2XL g2009__4547(.A (n_22), .B (n_0), .Y (n_2));
  CLKINVX1 g2016(.A (n_3), .Y (n_26));
  CLKINVX1 g2010(.A (n_1), .Y (n_11));
  NAND2XL g2018__9682(.A (state[1]), .B (n_46), .Y (n_3));
  CLKINVX1 g2011(.A (n_0), .Y (n_25));
  NAND2XL g2015__2683(.A (bit_cnt[0]), .B (bit_cnt[1]), .Y (n_0));
  NAND2XL g2013__1309(.A (bit_cnt[3]), .B (state[1]), .Y (n_1));
  NOR2XL g2014__6877(.A (bit_cnt[0]), .B (bit_cnt[1]), .Y (n_16));
  NOR2XL g2017__2900(.A (bit_cnt[2]), .B (state[0]), .Y (n_4));
  NOR2XL g2012__2391(.A (state[1]), .B (state[0]), .Y (n_14));
  NOR2BX1 g2020__7675(.AN (bit_cnt[0]), .B (bit_cnt[1]), .Y (n_15));
  NOR2BX1 g2019__7118(.AN (bit_cnt[1]), .B (bit_cnt[0]), .Y (n_20));
  INVXL g2024(.A (rst), .Y (n_48));
  DFFRX1 \bit_cnt_reg[3] (.RN (n_48), .CK (clk), .D (n_44), .Q
       (bit_cnt[3]), .QN (n_46));
  DFFRX1 \state_reg[0] (.RN (n_48), .CK (clk), .D (n_33), .Q
       (state[0]), .QN (n_42));
  DFFRX1 \bit_cnt_reg[2] (.RN (n_48), .CK (clk), .D (n_36), .Q
       (bit_cnt[2]), .QN (n_22));
endmodule


